gateway:
  frontend:
    http:
      host: "0.0.0.0"
      port: 8080
      readTimeout: 30
      writeTimeout: 30

  backend:
    http:
      maxIdleConns: 100
      maxIdleConnsPerHost: 10
      idleConnTimeout: 90

  registry:
    type: static
    static:
      services:
        - name: backend-service
          instances:
            - id: backend-1
              address: "localhost"
              port: 3000
              health: healthy

  router:
    rules:
      - id: backend-route
        path: /api/*
        serviceName: backend-service
        loadBalance: round_robin

  # Health check configuration with active backend monitoring
  health:
    enabled: true
    healthPath: /health
    readyPath: /ready
    livePath: /live
    checks:
      # Monitor backend service health
      backend-service:
        type: http
        interval: 30  # Check every 30 seconds
        timeout: 5    # 5 second timeout
        config:
          type: http  # Backend monitor will check all instances
      
      # Direct TCP check for database
      database:
        type: tcp
        interval: 60
        timeout: 3
        config:
          address: "localhost:5432"
      
      # You can also monitor specific endpoints
      api-health:
        type: http
        interval: 15
        timeout: 3
        config:
          url: "http://localhost:3000/health"