# Hot Reload Configuration Example
# This configuration demonstrates the hot reload feature
# Any changes to this file will be automatically applied without restarting the gateway

gateway:
  frontend:
    http:
      host: "0.0.0.0"
      port: 8080
      readTimeout: 30
      writeTimeout: 30

  backend:
    http:
      maxIdleConns: 100
      maxIdleConnsPerHost: 10
      idleConnTimeout: 90
      keepAlive: true
      keepAliveTimeout: 30
      dialTimeout: 10
      responseHeaderTimeout: 10

  registry:
    type: static
    static:
      services:
        - name: api-service
          instances:
            - id: api-1
              address: "127.0.0.1"
              port: 3000
              health: healthy
            - id: api-2
              address: "127.0.0.1"
              port: 3001
              health: healthy

  router:
    rules:
      - id: api-route
        path: /api/*
        serviceName: api-service
        loadBalance: round_robin
        timeout: 10

# Hot Reload Test Instructions:
# 1. Start the gateway with this config file
# 2. Make changes to this file (e.g., change port, add services, modify routes)
# 3. Save the file
# 4. The gateway will automatically reload the configuration
# 5. Check logs for "Configuration reloaded successfully" message
#
# Example changes to test:
# - Change frontend port from 8080 to 8081
# - Add a new service instance
# - Modify load balancing strategy
# - Add authentication requirements
# - Enable rate limiting