gateway:
  frontend:
    http:
      host: "0.0.0.0"
      port: 8080
      readTimeout: 30
      writeTimeout: 30
    websocket:
      enabled: true
      host: "0.0.0.0"
      port: 8081
      readTimeout: 60
      writeTimeout: 60
      handshakeTimeout: 10
      readBufferSize: 4096
      writeBufferSize: 4096
      enableCompression: false
      maxMessageSize: 1048576  # 1MB
      checkOrigin: true
      allowedOrigins:
        - "*"
  backend:
    http:
      maxIdleConns: 100
      maxIdleConnsPerHost: 10
      idleConnTimeout: 90
      keepAlive: true
      keepAliveTimeout: 30
      dialTimeout: 10
      responseHeaderTimeout: 10
    websocket:
      dialTimeout: 10
      handshakeTimeout: 10
      readBufferSize: 4096
      writeBufferSize: 4096
      maxMessageSize: 1048576  # 1MB
      poolSize: 10
  registry:
    type: static
    static:
      services:
        - name: websocket-echo-service
          instances:
            - id: echo-1
              address: "127.0.0.1"
              port: 3001
              health: healthy
        - name: chat-service
          instances:
            - id: chat-1
              address: "127.0.0.1"
              port: 3002
              health: healthy
            - id: chat-2
              address: "127.0.0.1"
              port: 3003
              health: healthy
  router:
    rules:
      # WebSocket echo service - no sticky session needed
      - id: websocket-echo
        path: /ws/echo
        methods: ["WEBSOCKET", "GET"]  # GET for upgrade
        serviceName: websocket-echo-service
        loadBalance: round_robin
        timeout: 60
      
      # WebSocket chat service - needs sticky sessions
      - id: websocket-chat
        path: /ws/chat/*
        methods: ["WEBSOCKET", "GET"]  # GET for upgrade
        serviceName: chat-service
        loadBalance: sticky_session
        timeout: 3600  # 1 hour for long-lived connections
        sessionAffinity:
          enabled: true
          ttl: 3600  # 1 hour
          source: cookie  # Extract session from cookie
          cookieName: CHAT_SESSION
      
      # Regular HTTP API
      - id: api-route
        path: /api/*
        serviceName: chat-service
        loadBalance: round_robin
        timeout: 30