version: '3.8'

services:
  # Gateway with static service discovery (secure alternative)
  gateway:
    build: .
    ports:
      - "8080:8080"     # HTTP
      - "8081:8081"     # WebSocket  
    volumes:
      - ./configs/gateway-static.yaml:/app/configs/gateway.yaml:ro
    environment:
      - LOG_LEVEL=debug
    depends_on:
      - backend1
      - backend2
    networks:
      - gateway-net

  # For Docker service discovery in production, use a secure proxy
  # docker-socket-proxy:
  #   image: tecnativa/docker-socket-proxy
  #   environment:
  #     - CONTAINERS=1  # Allow read access to containers
  #     - NETWORKS=1    # Allow read access to networks
  #     - SERVICES=1    # Allow read access to services
  #     - TASKS=1       # Allow read access to tasks (for swarm)
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - proxy-net
  #   restart: unless-stopped

  # Example backend service 1
  backend1:
    image: kennethreitz/httpbin
    labels:
      # Gateway service discovery labels
      - "gateway.enable=true"
      - "gateway.service=httpbin-service"
      - "gateway.port=80"
      - "gateway.meta.version=v1"
      - "gateway.meta.region=us-east"
    networks:
      - gateway-net

  # Example backend service 2
  backend2:
    image: kennethreitz/httpbin
    labels:
      - "gateway.enable=true"
      - "gateway.service=httpbin-service"
      - "gateway.port=80"
      - "gateway.meta.version=v1"
      - "gateway.meta.region=us-west"
    networks:
      - gateway-net

  # Example WebSocket service
  websocket-echo:
    build:
      context: .
      dockerfile: test/servers/websocket/Dockerfile
    labels:
      - "gateway.enable=true"
      - "gateway.service=websocket-service"
      - "gateway.port=3001"
      - "gateway.scheme=ws"
    networks:
      - gateway-net

  # Example SSE service
  sse-events:
    build:
      context: .
      dockerfile: test/servers/sse/Dockerfile
    labels:
      - "gateway.enable=true"
      - "gateway.service=sse-service"
      - "gateway.port=3010"
    networks:
      - gateway-net

networks:
  gateway-net:
    driver: bridge
  # proxy-net:
  #   driver: bridge