version: '3.8'

services:
  gateway:
    image: gateway:latest
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/etc/gateway/gateway.yaml:ro
    environment:
      - CONFIG_FILE=/etc/gateway/gateway.yaml
    depends_on:
      - service-a
      - service-b

  service-a:
    image: nginx:alpine
    volumes:
      - ./service-a.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8001"
      - "8002"

  service-b:
    image: nginx:alpine
    volumes:
      - ./service-b.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8003"